function opTr(){if(!$('tx').value.trim()&&exMode!=='mock'){alert('Load text first!');return}if(is){au.pause();is=0;updatePlBtn()}$('trM').classList.add('active');resTr();$('trA').disabled=0}
function tryClTr(){if(exMode==='mock'&&trIp){return}if($('rsV').style.display==='flex'){$('trM').classList.remove('active');return}if(trIp||$('trI').value.length>0){$('cfm').style.display='flex'}else{$('trM').classList.remove('active')}}
function cfmAct(a){$('cfm').style.display='none';if(a==='d'){$('trM').classList.remove('active');resTr()}else if(a==='s'){subTr()}}
function resTr(){trIp=0;clearInterval(trTi);$('trI').value='';$('trI').disabled=1;$('trA').disabled=0;$('trA').innerText='Start';$('trCD').textContent='00:00';$('trV').style.display='flex';$('rsV').style.display='none';$('trInf').textContent='Ready'}
function togTr(){if(trIp){subTr()}else{stTr(false)}}
function stTr(auto=false){const v=parseFloat($('trT').value)||parseFloat($('trC').value)||0;trStopW=(v===0);trDur=v*60;trRem=v*60;trElap=0;trIp=1;$('trI').disabled=0;$('trI').value='';$('trI').focus();$('trA').innerText='Submit';if(exMode==='mock')$('trA').innerText='Submit (Early)';clearInterval(trTi);trTi=setInterval(()=>{if(trStopW)trElap++;else trRem--;let t=trStopW?trElap:trRem,m=Math.floor(t/60),s=t%60;$('trCD').textContent=`${m}:${s<10?'0':''}${s}`;if(!trStopW&&trRem<=0)subTr()},1000)}
function subTr(){clearInterval(trTi);trIp=0;$('trI').disabled=1;$('trA').innerText='Start';const srcT=$('chkFull').checked?origTxt:$('tx').value;oToks=tok(srcT);uToks=tok($('trI').value);const m=oToks.length,n=uToks.length,d=Array.from({length:m+1},()=>new Float32Array(n+1).fill(1e9)),p=Array.from({length:m+1},()=>new Int8Array(n+1).fill(0));d[0][0]=0;for(let i=0;i<=m;i++)for(let j=0;j<=n;j++){if(i<m&&d[i+1][j]>d[i][j]+1){d[i+1][j]=d[i][j]+1;p[i+1][j]=1}if(j<n&&d[i][j+1]>d[i][j]+1){d[i][j+1]=d[i][j]+1;p[i][j+1]=2}if(i<m&&j<n){const c=cmpW(oToks[i].t,uToks[j].t);if(d[i+1][j+1]>d[i][j]+c){d[i+1][j+1]=d[i][j]+c;p[i+1][j+1]=0}}if(i<m&&j<n-1){const cm=cmpW(oToks[i].t,uToks[j].t+uToks[j+1].t);if(d[i+1][j+2]>d[i][j]+cm+0.1){d[i+1][j+2]=d[i][j]+cm+0.1;p[i+1][j+2]=3}}if(i<m-1&&j<n){const cs=cmpW(oToks[i].t+oToks[i+1].t,uToks[j].t);if(d[i+2][j+1]>d[i][j]+cs+0.1){d[i+2][j+1]=d[i][j]+cs+0.1;p[i+2][j+1]=4}}}diffs=[];let i=m,j=n;while(i>0||j>0){const op=p[i][j];if(op===0){const c=cmpW(oToks[i-1].t,uToks[j-1].t);diffs.unshift({t:c===0?'ok':(c<1?'h':'s'),o:oToks[i-1],u:uToks[j-1],i:i-1,j:j-1});i--;j--}else if(op===1){diffs.unshift({t:'m',o:oToks[i-1],u:null,i:i-1,j:-1});i--}else if(op===2){diffs.unshift({t:'i',o:null,u:uToks[j-1],i:-1,j:j-1});j--}else if(op===3){diffs.unshift({t:'h',o:oToks[i-1],u:{t:uToks[j-2].t+uToks[j-1].t},i:i-1,j:j-2,msg:'Split'});i--;j-=2}else if(op===4){diffs.unshift({t:'h',o:{t:oToks[i-2].t+oToks[i-1].t},u:uToks[j-1],i:i-2,j:j-1,msg:'Merge'});i-=2;j--}}$('trV').style.display='none';$('rsV').style.display='flex';$('tx').style.visibility='visible';reCalc()}
function reCalc(){if(!exRules||Object.keys(exRules).length===0)exRules={cap:0,com:0,pun:0.5,spl:0.5,sub:'s',max:100};let tE=0,tot=oToks.length;const r=exRules;diffs.forEach(e=>{e.v=0;if(e.t==='i'){e.v=r.sub==='d'?1:0.5}else if(e.t==='m'){e.v=1}else if(e.t==='s'){e.v=1}else if(e.t==='h'){e.v=parseFloat(r.spl)}else if(e.t==='ok'){if(e.o.t!==e.u.t){let ov=0;if(parseFloat(r.cap)>0&&e.o.t[0]!==e.u.t[0])ov=Math.max(ov,parseFloat(r.cap));if(e.o.t.match(/[.?!|\u0964]/)&&!e.u.t.match(/[.?!|\u0964]/))ov=Math.max(ov,parseFloat(r.pun));e.v=ov;if(ov>0)e.t='p'}}tE+=e.v});const acc=Math.max(0,100-(tE/tot*100)),pass=acc>=(100-parseFloat(r.max));$('resBox').style.display='flex';$('resBox').style.borderColor=pass?'var(--gr)':'var(--re)';$('resTit').innerHTML=`<span style="color:${pass?'var(--gr)':'var(--re)'}">${pass?'PASSED':'FAILED'}</span>`;$('resDet').innerHTML=`Errors: <b>${tE.toFixed(1)}</b> / ${tot} (${(tE/tot*100).toFixed(1)}%)<br>Accuracy: <b>${acc.toFixed(1)}%</b>`;renCheckV()}
function renCheckV(){const v=$('checkV');v.innerHTML='';$('rS').style.display='none';let cDiv=document.createElement('div');diffs.forEach((e,k)=>{let sp=document.createElement('span');sp.onclick=(ev)=>{ev.stopPropagation();showAct(k,ev.clientX,ev.clientY)};if(e.t==='i'){sp.className='c-ins';sp.textContent=e.u.t+' '}else if(e.t==='m'){sp.className='c-mis';sp.textContent=e.o.t+' '}else if(e.t==='s'||e.t==='h'||e.t==='p'){sp.innerHTML=`<span class="${e.t==='s'?'c-sub':'c-spl'}">${e.u.t}</span><span class="c-cor">[${e.o.t}]</span> `}else{sp.className='w-n';sp.textContent=e.u.t+' '}v.appendChild(sp);if(e.v>0){let mk=document.createElement('sup');mk.style.color='var(--re)';mk.style.fontSize='9px';mk.textContent=e.v;v.appendChild(mk)}});$('eL').innerHTML='';diffs.filter(x=>x.v>0).forEach((e,k)=>{const it=document.createElement('div');it.className='e-it';it.innerHTML=`<div class="row" style="margin:0"><span class="e-w ${e.t==='i'?'c-ins':(e.t==='m'?'c-mis':'c-sub')}">${e.u?e.u.t:'---'}</span> ➔ <span class="e-w c-cor">${e.o?e.o.t:'---'}</span> <span style="margin-left:auto;font-weight:bold">${e.v}</span></div>`;$('eL').appendChild(it)})}
function showAct(k,x,y){const d=$('actM')||document.createElement('div');d.id='actM';d.className='ctx-menu';d.innerHTML=`<div onclick="modEr(${k},'f')">Full Err</div><div onclick="modEr(${k},'h')">Half Err</div><div onclick="modEr(${k},'i')">Ignore</div>`;document.body.appendChild(d);d.style.left=x+'px';d.style.top=y+'px';const cl=()=>{d.remove();document.removeEventListener('click',cl)};setTimeout(()=>document.addEventListener('click',cl),10)}
function modEr(k,a){const e=diffs[k];if(a==='f'){e.t='s';e.v=1}else if(a==='h'){e.t='h';e.v=0.5}else{e.t='ok';e.v=0}reCalc()}
function refine(){$('rsV').style.display='none';$('trV').style.display='flex';$('trI').disabled=0;$('trI').focus()}
