let ac,sr,gn,is=0,curL=[],filtL=[],curI=-1,bpAb=null,curO={},curS=1,curT=14,maxW=0,trTi=null,trRem=0,trElap=0,trStopW=0,trDur=0,trIp=0,errs=[],oToks=[],uToks=[],lastAuSrc=null;
let exMode='practice',curEx='custom',mockState=0,mockTimer=null,exRules={},crpS=0,crpE=0,origTxt='';
const $=(i)=>document.getElementById(i),au=$('au'),regs=[{u:"d82c26e4cb069d8f5b9d1f2a5cf42e24",t:"Eng"},{u:"363e6ce7f8e1b41be69bba7623c7c320",t:"Hin"}];
const exams={
ssc_d:{name:'SSC Gr D',wpm:80,dur:10,read:10,trans:65,lg:'ssc',rules:{cap:1,com:1,pun:1,spl:1,sub:'s',wc:'s',max:5}},
ssc_c:{name:'SSC Gr C',wpm:100,dur:10,read:10,trans:40,lg:'ssc',rules:{cap:1,com:1,pun:1,spl:1,sub:'s',wc:'s',max:5}},
custom:{name:'Custom',wpm:80,dur:10,read:0,trans:0,lg:'std',rules:{cap:0,com:0,pun:0.5,spl:1,sub:'s',wc:'s',max:100}}
};
const clean=(s)=>s.replace(/[\u2018\u2019\u201c\u201d]/g,"'").replace(/[\u2013\u2014]/g,"-").trim();
const bare=(s)=>clean(s).toLowerCase().replace(/[.।!?;:,|]/g,'');
const tok=(t)=>{let r=[],re=/\S+/g,m;while((m=re.exec(t))!==null)r.push({t:m[0],s:m.index,e:re.lastIndex});return r};
function clnAu(){if(lastAuSrc){URL.revokeObjectURL(lastAuSrc);lastAuSrc=null}}
function toggleTheme(){document.body.classList.toggle('light-mode',$('theme').checked)}
function resetData(){$('tx').value='';$('stTitle').innerText='No Audio';clnAu();$('wc').value=0;$('st').innerText='Ready';$('trI').value='';$('trI').disabled=0;$('resBox').style.display='none';$('rS').innerHTML='';$('checkV').innerHTML='';$('eL').innerHTML='';upWC();if(is)au.pause();is=0;updatePlBtn();crpS=0;crpE=0;origTxt=''}
function updateStatus(){$('stWPM').textContent=$('wi').value+' WPM';$('stRate').textContent=$('ri').value+'x';$('stWC').textContent=$('wc').value+' W';$('stMode').textContent=exMode==='mock'?'Mock Mode':'Practice';$('stMode').style.color=exMode==='mock'?'#ef4444':'inherit'}
function upWC(force=false){const t=$('tx').value.trim(),l=exRules.wc||$('lg').value;let w=0;if(t){if(l==='s')w=t.replace(/\s/g,'').length/5;else if(l==='sp')w=(t.length-t.split(/\s+/).length+1)/5;else if(l==='p'){const tk=t.split(/\s+/);let sm=0,lg=0;tk.forEach(x=>{if(x.match(/[,;]/))sm++;if(x.match(/[.?!|\u0964]/))lg++});w=tk.length+(sm*0.5)+(lg*1)}else w=t.split(/\s+/).length}const val=Math.ceil(w);$('wc').value=val;$('st').textContent='W: '+val;if(force||val>0)sync('w');updateStatus()}
function init(){regs.forEach(r=>{let o=document.createElement('option');o.value=r.u;o.textContent=r.t;$('rg').appendChild(o)});[40,50,60,80,90,100,120,140,160,180,200].forEach(v=>{let o=document.createElement('option');o.value=v;o.textContent=v;$('ws').appendChild(o)});[0.8,1,1.2,1.5].forEach(v=>{let o=document.createElement('option');o.value=v;o.textContent=v;$('rs').appendChild(o)});$('rg').onchange=e=>lG(e.target.value);$('f').onchange=async e=>{resetData();let aud=0,txt=0;for(const f of Array.from(e.target.files)){if(f.type.includes('audio')){clnAu();lastAuSrc=URL.createObjectURL(f);au.src=lastAuSrc;meta(f.name);aud=1}else if(f.name.match(/\.(txt|md)$/i)||f.type.includes('text')){const t=await f.text();$('tx').value=t;origTxt=t;txt=1}}setTimeout(()=>{if(txt)upWC(true);if(aud&&txt)prepMock()},500)};lG(null);upExD()}
function meta(n){$('stTitle').innerText=n;updateStatus()}
function setP(v){const[min,max]=v.split('-');uSl('min',min);uSl('max',max==='max'?maxW:max)}
function uSl(t,v){let val=parseInt(v)||0;if(t==='min'){$('wMin').value=val;$('slMi').value=val}else{$('wMax').value=val;$('slMa').value=val}renL()}
function adj(k,v){if(k==='sc'){curS=Math.max(0.5,Math.min(1.5,curS+v));document.documentElement.style.setProperty('--sc',curS)}else{curT=Math.max(10,Math.min(48,curT+v));document.documentElement.style.setProperty('--ts',curT+'px')}}
function openM(){$('md').classList.toggle('active')}
function openEx(){$('exM').classList.add('active')}
function upExD(){const s=$('exSel').value,m=$('exMode').value;if(s==='custom'){$('custOpts').style.display='flex';exams.custom.wpm=$('cWpm').value;exams.custom.dur=$('cDur').value}else{$('custOpts').style.display='none'}const e=exams[s];$('exDesc').innerText=`${e.name} | ${e.dur}m @ ${e.wpm}wpm | Rules: ${e.rules.wc.toUpperCase()}`;if(s==='custom')e.rules={cap:$('cCap').value,com:$('cCom').value,pun:$('cPun').value,spl:$('cSpl').value,sub:$('cSub').value,wc:$('cLg').value,max:$('cMaxE').value}}
function selEx(){curEx=$('exSel').value;exMode=$('exMode').value;exRules={...exams[curEx].rules};$('lg').value=exRules.wc;$('exM').classList.remove('active');$('srcM').classList.add('active')}
function prepMock(){const e=exams[curEx],wpm=parseInt(e.wpm),dur=parseInt(e.dur),tgW=wpm*dur;$('wi').value=wpm;sync('w');const auD=au.duration;const exD=dur*60;if(exMode==='mock'&&auD>exD+30){$('crpM').classList.add('active')}else{startMock()}}
function setCrp(p){const e=exams[curEx],wpm=parseInt(e.wpm),dur=parseInt(e.dur),tgW=wpm*dur;const auD=au.duration,reqD=dur*60;$('crpM').classList.remove('active');if(p==='s'){crpS=0;crpE=reqD+15;cropTxt(0,tgW)}else if(p==='m'){crpS=(auD/2)-(reqD/2)-15;crpE=crpS+reqD+30;cropTxt('mid',tgW)}else{crpE=auD;crpS=auD-reqD-15;cropTxt('end',tgW)}startMock()}
function cropTxt(pos,cnt){if(!origTxt)origTxt=$('tx').value;const t=origTxt.split(/\s+/);if(t.length<=cnt){$('tx').value=origTxt;return}let sl;if(pos===0)sl=t.slice(0,cnt+20);else if(pos==='mid'){const mid=Math.floor(t.length/2);sl=t.slice(mid-(cnt/2),mid+(cnt/2)+20)}else sl=t.slice(t.length-cnt-20);$('tx').value=sl.join(' ')+' ...';upWC(true)}
function startMock(){const e=exams[curEx];if(exMode==='mock'){$('tx').style.visibility='hidden';$('mockOV').style.display='flex';mockState=0;nextMockStep()}else{$('trT').value=e.trans>0?e.trans:0;$('trC').value=e.trans;updateStatus()}}
function nextMockStep(){const e=exams[curEx];clearInterval(mockTimer);mockState++;$('mSkipBtn').onclick=()=>nextMockStep();if(mockState===1){$('mStT').innerText='Dictation';$('mSub').innerText='Playing Audio...';$('mSkipBtn').innerText='Finish Early';au.currentTime=crpS;au.play();is=1;updatePlBtn();if(crpE>0){au.ontimeupdate=()=>{if(au.currentTime>=crpE){au.pause();beeps();nextMockStep()}}}else{au.onended=()=>nextMockStep()}$('mTimer').innerText='--:--'}else if(mockState===2){is=0;updatePlBtn();runMockTimer(15,'Break / Gap','Prepare for reading...',()=>nextMockStep())}else if(mockState===3){runMockTimer(e.read*60,'Reading Time','Read your notes...',()=>nextMockStep())}else if(mockState===4){$('mockOV').style.display='none';$('trM').classList.add('active');resTr();$('trT').value=e.trans;$('trC').value=e.trans;$('trA').disabled=1;let cd=10;$('trInf').innerText=`Auto-start in ${cd}s`;const cdt=setInterval(()=>{cd--;$('trInf').innerText=`Auto-start in ${cd}s`;if(cd<=0){clearInterval(cdt);stTr(true)}},1000)}}
function runMockTimer(sec,t,s,cb){$('mStT').innerText=t;$('mSub').innerText=s;$('mSkipBtn').innerText='Skip';let rem=sec;const upd=()=>{const m=Math.floor(rem/60),s=rem%60;$('mTimer').innerText=`${m}:${s<10?'0':''}${s}`};upd();mockTimer=setInterval(()=>{rem--;upd();if(rem<=0){clearInterval(mockTimer);cb()}},1000)}
async function lG(u){let list=[];try{for(let r of(u?[regs.find(x=>x.u===u)]:regs)){const res=await fetch(`https://gist.githubusercontent.com/vs-parihar/${r.u}/raw?t=${Date.now()}`);const j=await res.json();if(Array.isArray(j))list=list.concat(j.map(i=>({...i,reg:r.t})))}}catch(e){}lD(list);renT();renL()}
function lD(list){maxW=0;curL=list.map((i,idx)=>{let m=i.title.match(/WORDS\s*(\d+)/i),w=i.w||[],b=Math.max(...w,m?parseInt(m[1]):0);if(b>maxW)maxW=b;return{...i,_id:idx,maxW:b,tags:(i.tags||[]).map(t=>t.toUpperCase())}});$('slMi').max=$('slMi').value=$('slMa').max=$('slMa').value=maxW;uSl('min',0);uSl('max',maxW)}
function gW(i){const l=$('lg').value;if(i.w){if(l==='s')return i.w[0];if(l==='sp')return i.w[1];return i.w[2]}return i.maxW||0}
function renT(){const t=$('tags'),set=new Set();curL.forEach(i=>i.tags.forEach(g=>set.add(g)));t.innerHTML='';Array.from(set).sort().forEach(g=>{let s=document.createElement('span');s.className='filter-chip';s.textContent=g;s.onclick=()=>{s.classList.toggle('active');renL()};t.appendChild(s)})}
function renL(){const mi=parseInt($('wMin').value)||0,ma=parseInt($('wMax').value)||maxW,at=Array.from(document.querySelectorAll('.filter-chip.active')).map(x=>x.textContent),so=$('srt').value;filtL=curL.filter(i=>{const v=gW(i);return(v>=mi&&v<=ma)&&(at.length===0||at.every(t=>i.tags.includes(t)))});if(so==='on')filtL.sort((a,b)=>a._id-b._id);if(so==='no')filtL.sort((a,b)=>b._id-a._id);if(so==='az')filtL.sort((a,b)=>a.title.localeCompare(b.title));if(so==='sl')filtL.sort((a,b)=>gW(a)-gW(b));if(so==='ls')filtL.sort((a,b)=>gW(b)-gW(a));if(so==='sh'){for(let i=filtL.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[filtL[i],filtL[j]]=[filtL[j],filtL[i]]}}$('ls').innerHTML='';filtL.forEach((i,idx)=>{let d=document.createElement('div');d.className='list-item';d.innerHTML=`<div style="font-weight:500">${i.title}</div><div style="font-size:9px;opacity:0.7">${gW(i)} words • ${fT(i.dur||0)}</div>`;d.onclick=()=>lA(i,idx);$('ls').appendChild(d)})}
async function lA(i,idx){curI=idx;curO=i;openM();$('tx').value="Loading...";const v=gW(i);if(v){$('wc').value=v;$('st').innerText='W: '+v;if(i.dur){$('wi').value=(v/(i.dur/60)).toFixed(2);$('ri').value="1.0000";sync('r')}}const id=i.url?.split('details/')[1],dl=`https://archive.org/download/${id}/`;let auSrc=i.audio;try{if(id){const mr=await fetch(`https://archive.org/metadata/${id}`),md=await mr.json(),fs=md.files||[];const mf=fs.find(f=>f.name.endsWith('.mp3')),of=fs.find(f=>f.name.match(/\.(wav|m4a|ogg|aac)$/i)),tf=fs.find(f=>f.name.endsWith('.txt')||f.name.endsWith('.md'));if(mf)auSrc=dl+mf.name;else if(of)auSrc=dl+of.name;if(i.matter){const r=await fetch(i.matter);$('tx').value=await r.text()}else if(tf){const r=await fetch(dl+tf.name);$('tx').value=await r.text()}else{$('tx').value=md.metadata.description?.replace(/<[^>]*>?/gm,'')||"No text"}}}catch(e){if(!i.matter)$('tx').value="Text Load Fail"}clnAu();au.src=auSrc;au.load();meta(i.title);origTxt=$('tx').value;upWC();if(exMode==='mock')prepMock()}
function sync(s){const w=parseFloat($('wc').value),m=au.duration/60;if(!m||!w)return;if(s==='w'){$('ri').value=(parseFloat($('wi').value)/(w/m)).toFixed(4);au.playbackRate=Math.max(0.1,parseFloat($('ri').value))}else{const wpm=((w/m)*parseFloat($('ri').value));$('wi').value=wpm.toFixed(2);au.playbackRate=Math.max(0.1,parseFloat($('ri').value))}const ws=$('ws'),wv=$('wi').value;ws.value=[...ws.options].some(o=>o.value===wv)?wv:"";updateStatus()}
function dS(k,v){if(!v)return;if(k==='w')$('wi').value=v;else $('ri').value=v}
function adW(d){$('wi').value=(parseFloat($('wi').value||0)+d).toFixed(2);sync('w')}
function adR(d){$('ri').value=(parseFloat($('ri').value||1)+d).toFixed(4);sync('r')}
function upV(){if(gn)gn.gain.value=$('vl').value}
$('wi').oninput=()=>sync('w');$('ri').oninput=()=>sync('r');
function updatePlBtn(){$('pl').innerHTML=is?'<svg viewBox="0 0 24 24"><path d="M6 19h4V5H6v14zm8-14v14h4V5h-4z"/></svg>':'<svg viewBox="0 0 24 24"><path d="M8 5v14l11-7z"/></svg>';if(is)$('pl').classList.add('pausing');else $('pl').classList.remove('pausing')}
$('pl').onclick=async()=>{if(!ac){ac=new(window.AudioContext||window.webkitAudioContext)();sr=ac.createMediaElementSource(au);gn=ac.createGain();sr.connect(gn);gn.connect(ac.destination);upV()}if(is){au.pause();is=0;updatePlBtn()}else{if($('bp').checked&&au.currentTime<0.5){bpAb=new AbortController();try{await beeps(bpAb.signal)}catch(e){return}}await ac.resume();au.play();is=1;updatePlBtn()}};
$('sb').onclick=async()=>{if(bpAb)bpAb.abort();au.pause();au.currentTime=0;is=0;updatePlBtn()};
async function beeps(sig){for(let i=0;i<3;i++){const o=ac.createOscillator(),g=ac.createGain();o.connect(g);g.connect(ac.destination);g.gain.value=0.05;o.frequency.value=880;o.start();o.stop(ac.currentTime+0.1);await new Promise(r=>setTimeout(r,500))}}
function sk(s){au.currentTime+=s}
au.ontimeupdate=()=>{if(!au.duration)return;const d=au.duration,c=au.currentTime,p=(c/d)*100,w=parseFloat($('wi').value)||150,lagS=(20/w)*60,effD=d-lagS*2,relC=Math.max(0,c-lagS),relP=effD>0?Math.min(100,relC/effD*100):p;$('pf').style.width=p+'%';$('tm').textContent=`${fT(c/au.playbackRate)}/${fT(d/au.playbackRate)}`;if($('as').checked){const m=$('tx').scrollHeight-$('tx').clientHeight;$('tx').scrollTop=(relP/100)*m}};
function fT(s){const m=Math.floor(s/60),x=Math.floor(s%60);return`${m}:${x<10?'0':''}${x}`}
$('pb').onclick=e=>{const r=$('pb').getBoundingClientRect();au.currentTime=((e.clientX-r.left)/r.width)*au.duration};
async function expA(){const b=$('exB'),r=parseFloat($('ri').value),id=curO.url?.split('details/')[1],dl=`https://archive.org/download/${id}/`;let srcU=au.src;b.classList.add('exporting');b.innerText='⌛';if(id){try{const mr=await fetch(`https://archive.org/metadata/${id}`),md=await mr.json(),fs=md.files||[];const bf=fs.find(f=>f.name.endsWith('.wav'))||fs.find(f=>f.name.endsWith('.flac'))||fs.find(f=>f.name.endsWith('.m4a'))||fs.find(f=>f.name.endsWith('.mp3'));if(bf)srcU=dl+bf.name}catch(e){}}try{const res=await fetch(srcU),buf=await res.arrayBuffer(),ctx=new OfflineAudioContext(2,buf.byteLength/r,44100),sBuf=await ctx.decodeAudioData(buf),src=ctx.createBufferSource();src.buffer=sBuf;src.playbackRate.value=r;src.connect(ctx.destination);src.start();const ren=await ctx.startRendering(),blob=new Blob([toWav(ren)],{type:'audio/wav'}),name=`${(curO.title||'audio').replace(/WPM\d+/i,'')}WPM${Math.round($('wi').value)}`;const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name+'.wav';a.click();const tBlob=new Blob([$('tx').value],{type:'text/plain'}),tA=document.createElement('a');tA.href=URL.createObjectURL(tBlob);tA.download=name+'.txt';tA.click()}catch(e){}finally{b.classList.remove('exporting');b.innerText='⬇️'}}
function toWav(b){let n=b.numberOfChannels,len=b.length*n*2+44,buf=new ArrayBuffer(len),v=new DataView(buf),pos=0,s=(st,s)=>{for(let i=0;i<s.length;i++)v.setUint8(st+i,s.charCodeAt(i))};s(0,'RIFF');v.setUint32(4,len-8,true);s(8,'WAVE');s(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,n,true);v.setUint32(24,b.sampleRate,true);v.setUint32(28,b.sampleRate*n*2,true);v.setUint16(32,n*2,true);v.setUint16(34,16,true);s(36,'data');v.setUint32(40,len-44,true);pos=44;for(let i=0;i<b.length;i++)for(let c=0;c<n;c++){let x=Math.max(-1,Math.min(1,b.getChannelData(c)[i]));v.setInt16(pos,x<0?x*0x8000:x*0x7FFF,true);pos+=2}return buf}
function opTr(){if(!$('tx').value.trim()&&exMode!=='mock'){alert('Load text first!');return}if(is){au.pause();is=0;updatePlBtn()}$('trM').classList.add('active');resTr();$('trA').disabled=0}
function tryClTr(){if(exMode==='mock'&&trIp){return}if($('rsV').style.display==='flex'){$('trM').classList.remove('active');return}if(trIp||$('trI').value.length>0){$('cfm').style.display='flex'}else{$('trM').classList.remove('active')}}
function cfmAct(a){$('cfm').style.display='none';if(a==='d'){$('trM').classList.remove('active');resTr()}else if(a==='s'){subTr()}}
function resTr(){trIp=0;clearInterval(trTi);$('trI').value='';$('trI').disabled=1;$('trA').disabled=0;$('trA').innerText='Start';$('trCD').textContent='00:00';$('trV').style.display='flex';$('rsV').style.display='none';$('trInf').textContent='Ready'}
function togTr(){if(trIp){subTr()}else{stTr(false)}}
function stTr(auto=false){const v=parseFloat($('trT').value)||parseFloat($('trC').value)||0;trStopW=(v===0);trDur=v*60;trRem=v*60;trElap=0;trIp=1;$('trI').disabled=0;$('trI').value='';$('trI').focus();$('trA').innerText='Submit';if(exMode==='mock')$('trA').innerText='Submit (Early)';clearInterval(trTi);trTi=setInterval(()=>{if(trStopW)trElap++;else trRem--;let t=trStopW?trElap:trRem,m=Math.floor(t/60),s=t%60;$('trCD').textContent=`${m}:${s<10?'0':''}${s}`;if(!trStopW&&trRem<=0)subTr()},1000)}
function subTr(){clearInterval(trTi);trIp=0;$('trI').disabled=1;$('trA').innerText='Start';const srcT=$('chkFull').checked?origTxt:$('tx').value;oToks=tok(srcT);uToks=tok($('trI').value);const m=oToks.length,n=uToks.length,dp=Array.from({length:m+1},()=>new Int32Array(n+1));const hs={'में':'मैं','मैं':'में','की':'कि','कि':'की','ओर':'और','और':'ओर','है':'हैं','हैं':'है'};for(let i=1;i<=m;i++)for(let j=1;j<=n;j++){const bo=bare(oToks[i-1].t),bu=bare(uToks[j-1].t);dp[i][j]=(bo===bu||hs[bo]===bu)?dp[i-1][j-1]+1:Math.max(dp[i-1][j],dp[i][j-1])}let i=m,j=n;errs=[];while(i>0||j>0){const bo=i>0?bare(oToks[i-1].t):'',bu=j>0?bare(uToks[j-1].t):'';if(i>0&&j>0&&(bo===bu||hs[bo]===bu)){const o=clean(oToks[i-1].t),u=clean(uToks[j-1].t);if(o!==u){let ty='h';errs.unshift({t:ty,o:oToks[i-1],u:uToks[j-1],i:i-1,j:j-1,ok:1})}else errs.unshift({t:'w',o:oToks[i-1],u:uToks[j-1],i:i-1,j:j-1,ok:1});i--;j--}else if(j>0&&(i===0||dp[i][j-1]>=dp[i-1][j])){errs.unshift({t:'f',u:uToks[j-1],j:j-1,i:-1});j--}else{errs.unshift({t:'m',o:oToks[i-1],i:i-1,j:-1});i--}}$('trV').style.display='none';$('rsV').style.display='flex';$('tx').style.visibility='visible';renCheckV();reCalc()}
function renCheckV(){const v=$('checkV'),r=$('rS'),srcT=$('chkFull').checked?origTxt:$('tx').value;v.innerHTML='';r.innerHTML='';let sIdx=0;oToks.forEach((tok,idx)=>{if(tok.s>sIdx)r.appendChild(document.createTextNode(srcT.slice(sIdx,tok.s)));let sp=document.createElement('span');sp.textContent=tok.t;sp.className='w-n';sp.id=`o-${idx}`;sp.onclick=()=>revClick('o',idx);r.appendChild(sp);sIdx=tok.e});errs.forEach((e,k)=>{let sp=document.createElement('span');sp.id=`u-${k}`;sp.onclick=()=>revClick('u',k);if(e.t==='f'){sp.className='c-ins';sp.textContent=e.u.t+' '}else if(e.t==='m'){sp.className='c-mis';sp.textContent=e.o.t+' '}else if(e.t==='h'){sp.className='c-sp';sp.textContent=e.u.t+' '}else if(e.t==='d'){sp.className='c-dbl';sp.textContent=e.u.t+' '}else{sp.className='w-n';sp.textContent=e.u.t+' '}v.appendChild(sp)})}
function reCalc(){let tE=0,tot=oToks.length;const r=exRules;errs.forEach(e=>{let v=0;if(e.t==='f'){v=r.sub==='d'?1:0.5}else if(e.t==='m'){v=1}else if(e.t==='d'){v=1}else if(e.t==='h'){v=parseFloat(r.spl)}else if(e.t==='w'){if(e.o.t!==e.u.t){if(parseFloat(r.cap)>0&&e.o.t[0]!==e.u.t[0])v=Math.max(v,parseFloat(r.cap));if(e.o.t.match(/[,]/)&&!e.u.t.match(/[,]/))v=Math.max(v,parseFloat(r.com));if(e.o.t.match(/[.?!|]/)&&!e.u.t.match(/[.?!|]/))v=Math.max(v,parseFloat(r.pun))}}tE+=v});const acc=Math.max(0,100-(tE/tot*100)),pass=acc>=(100-parseFloat(r.max));$('resBox').style.display='flex';$('resBox').style.borderColor=pass?'var(--gr)':'var(--re)';$('resTit').innerHTML=`<span style="color:${pass?'var(--gr)':'var(--re)'}">${pass?'PASSED':'FAILED'}</span>`;$('resDet').innerHTML=`Errors: <b>${tE.toFixed(1)}</b> / ${tot} (${(tE/tot*100).toFixed(1)}%)<br>Accuracy: <b>${acc.toFixed(1)}%</b><br>Max Allowed Err: ${r.max}%`;const l=$('eL');l.innerHTML='';errs.forEach((e,k)=>{if(e.t==='w'||e.t==='x')return;const it=document.createElement('div');it.className='e-it';it.id=`err-${k}`;it.innerHTML=`<div class="row" style="margin:0"><span class="e-ctx">${getCtx(oToks,e.i,2,-1)}</span><span class="e-w ${e.t==='f'?'m-err':(e.t==='h'?'m-h':(e.t==='d'?'m-d':'m-mis'))}" onclick="jump(${k})">${e.t==='m'?e.o.t:e.u.t}</span><span class="e-ctx">${getCtx(oToks,e.i,2,1)}</span></div><div class="row" style="margin-top:2px"><button class="xs-btn" onclick="upEr(${k},'f')" style="border-color:var(--re)">F</button><button class="xs-btn" onclick="upEr(${k},'h')" style="border-color:var(--bd)">H</button><button class="xs-btn" onclick="upEr(${k},'d')" style="border-color:var(--re)">D</button><button class="xs-btn" onclick="upEr(${k},'x')">X</button></div>`;l.appendChild(it)})}
function getCtx(tk,idx,c,dir){if(idx<0)return"";let s=[],cnt=0,curr=idx+dir;while(cnt<c&&curr>=0&&curr<tk.length){if(dir<0)s.unshift(tk[curr].t);else s.push(tk[curr].t);curr+=dir;cnt++}return s.join(' ')}
function revClick(type,idx){let k=-1;if(type==='o'){k=errs.findIndex(e=>e.i===idx)}else{k=idx}if(k!==-1)jump(k)}
function jump(k){const e=errs[k];if(!e)return;clrHl();const hl=(id,off)=>{const el=$(id);if(el)el.classList.add('ctx-hl')};let idxInO=e.i,idxInU=k;if(idxInO!==-1){hl(`o-${idxInO-1}`);hl(`o-${idxInO-2}`);hl(`o-${idxInO+1}`);hl(`o-${idxInO+2}`);const el=$(`o-${idxInO}`);if(el)el.scrollIntoView({behavior:'smooth',block:'center'})}if(idxInU!==-1){const uEl=$(`u-${idxInU}`);if(uEl){uEl.scrollIntoView({behavior:'smooth',block:'center'});for(let i=1;i<=2;i++){hl(`u-${idxInU-i}`);hl(`u-${idxInU+i}`)}}}const elItem=$(`err-${k}`);if(elItem){elItem.scrollIntoView({behavior:'smooth',block:'center'});[...$('eL').children].forEach(c=>c.classList.remove('active'));elItem.classList.add('active')}}
function clrHl(){[...document.querySelectorAll('.ctx-hl')].forEach(e=>e.classList.remove('ctx-hl'))}
function upEr(k,t){errs[k].t=t;reCalc();renCheckV();jump(k)}
function refine(){$('rsV').style.display='none';$('trV').style.display='flex';$('trI').disabled=0;$('trI').focus();$('trA').innerText='Submit';$('trA').disabled=0;trIp=1}
window.onload=init;
